### ISSUE TITLE
App Problem

### ISSUE THREAD

**Issue by tzuuuu** [JarrenPoh/upoint_web#6]
**1. 報名表單 自動帶入問題**
![S__2088969](https://github.com/JarrenPoh/upoint_web/assets/116798227/b7d3f72c-ce9c-4d5d-91d4-782b0f58962d)
![S__2088967](https://github.com/JarrenPoh/upoint_web/assets/116798227/5ff18b02-214d-40a9-b02d-61be4862fd97)
**2. 資訊看不到**
![S__2088980](https://github.com/JarrenPoh/upoint_web/assets/116798227/58c8fef5-5ec1-4e19-9d8f-2858580d06a6)

**Comment by JarrenPoh** [comment]
issue 移轉到https://github.com/JarrenPoh/upoint_app/issues/4
