### ISSUE TITLE
活動分類 載入錯誤

### ISSUE THREAD

**Issue by HuangJoseph710** [JarrenPoh/upoint_web#7]
切換分類選項後，並不是每次都能顯示正確資訊。
可能是切換分類後，只更新到圖片，活動的時間、地點、獎勵 沒有被更新到。

以下兩個照片裡的活動簡介都是錯誤的。
![image](https://github.com/JarrenPoh/upoint_web/assets/102664358/390c5ac3-5b2c-42b9-8441-f467c312dce9)
![image](https://github.com/JarrenPoh/upoint_web/assets/102664358/2b63dcba-d055-4668-be06-04de3db6d54e)

**Comment by JarrenPoh** [comment]
已修正。

感謝 非常詳細的敘述錯誤～
